[package]
name = "sgx-types"
version = "0.1.0"
authors = ["Rafał Wojdyła <omeg@invisiblethingslab.com>"]
edition = "2018"

[features]
default = []
verbose = []
with-serde = ['serde']

[dependencies]
byteorder = "1.3"
hex = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
