[package]
name = "sgx-types"
version = "0.1.0"
authors = ["Rafał Wojdyła <omeg@invisiblethingslab.com>"]
edition = "2018"

[features]
default = []
verbose = []

[dependencies]
byteorder = "1.3"
hex = "0.4"
